LANGUAGES = {
    "en": {
        "lang_name": "English",
        "is_rtl": "false",
        "window_title": "PCLink Server",
        "admin_suffix": " (Administrator)",
        "server_running_status": "Server is RUNNING",
        "server_stopped_status": "Server is STOPPED",
        "protocol_https_secure": "Secure (HTTPS)",
        "protocol_http_unsecure": "Insecure (HTTP)",
        "start_server_btn": "Start Server",
        "stop_server_btn": "Stop Server",
        "ip_addr_label": "IP Address:",
        "port_label": "Port:",
        "api_key_label": "API Key:",
        "copy_ip_tooltip": "Copy IP Address",
        "copy_port_tooltip": "Copy Port",
        "copy_key_tooltip": "Copy API Key",
        "qr_stopped_text": "Server is stopped. Start the server to show the QR code.",
        "qr_error_text": "Could not generate QR code. Check if the server is running.",
        "devices_group": "Connected Devices",
        "devices_waiting_text": "Waiting for devices to connect...",
        "devices_stopped_text": "Server is stopped.",
        "menu_file": "&File",
        "menu_file_exit": "E&xit",
        "menu_file_restart_admin": "&Restart as Administrator",
        "menu_file_about": "&About PCLink",
        "menu_settings": "&Settings",
        "change_port_btn": "Change &Port...",
        "regen_api_key_btn": "&Regenerate API Key...",
        "menu_language": "&Language",
        "language_changed_title": "Language Change",
        "language_changed_msg": "The language will change the next time you start the application.",
        "start_with_os_chk": "Start with Operating System",
        "start_with_os_tooltip": "If checked, PCLink will start automatically when you log in.",
        "minimize_on_close_chk": "Minimize to Tray on Close",
        "use_https_chk": "Use Secure Connection (HTTPS)",
        "use_https_tooltip": "Enables SSL/TLS encryption. Recommended.",
        "allow_insecure_shell_chk": "Allow Insecure Shell Access",
        "allow_insecure_shell_tooltip": "WARNING: Allows the terminal to run without API key authentication. Use only on trusted networks.",
        "show_startup_notification_chk": "Show Notification on Startup",
        "tray_tooltip": "PCLink Server",
        "tray_show": "Show PCLink",
        "setting_saved_title": "Setting Saved",
        "restart_server_prompt": "The server must be restarted for this change to take effect. Restart server now?",
        "regen_api_key_confirm": "Are you sure you want to generate a new API key? All currently connected devices will need to be re-paired.",
        "api_key_updated_title": "API Key Updated",
        "api_key_updated_msg": "A new API key has been generated successfully.",
        "change_port_prompt": "Enter the new port for the server:",
        "https_warning_title": "Security Warning",
        "https_warning_msg": "Disabling HTTPS is not recommended. Your connection will not be encrypted.",
        "insecure_shell_warning_title": "Security Warning",
        "insecure_shell_warning_msg": "Enabling this allows anyone on your network to access the server's terminal. This is a significant security risk. Are you sure you want to proceed?",
        "confirm_exit_title": "Confirm Exit",
        "confirm_exit_text": "Are you sure you want to exit? The server will be stopped.",
        "exit_button": "Exit",
        "minimize_button": "Minimize to Tray",
        "cancel_button": "Cancel",
        "check_updates_on_startup_chk": "Check for Updates on Startup",
        "check_updates_now_btn": "Check for Updates Now",
        "update_available_title": "Update Available",
        "update_available_msg": "A new version of PCLink is available.",
        "no_updates_title": "No Updates",
        "no_updates_msg": "You are running the latest version of PCLink.",
        "pairing_request_title": "Device Pairing Request",
        "pairing_request_text": "Device '{device_name}' wants to connect to this server. Allow connection?",
    },
    "ar": {
        "lang_name": "العربية",
        "is_rtl": "true",
        "window_title": "خادم PCLink",
        "admin_suffix": " (مسؤول)",
        "server_running_status": "الخادم يعمل",
        "server_stopped_status": "الخادم متوقف",
        "protocol_https_secure": "آمن (HTTPS)",
        "protocol_http_unsecure": "غير آمن (HTTP)",
        "start_server_btn": "بدء الخادم",
        "stop_server_btn": "إيقاف الخادم",
        "ip_addr_label": "عنوان IP:",
        "port_label": "المنفذ:",
        "api_key_label": "مفتاح API:",
        "copy_ip_tooltip": "نسخ عنوان IP",
        "copy_port_tooltip": "نسخ المنفذ",
        "copy_key_tooltip": "نسخ مفتاح API",
        "qr_stopped_text": "الخادم متوقف. ابدأ الخادم لإظهار رمز الاستجابة السريعة.",
        "qr_error_text": "لا يمكن إنشاء رمز الاستجابة السريعة. تحقق مما إذا كان الخادم يعمل.",
        "devices_group": "الأجهزة المتصلة",
        "devices_waiting_text": "في انتظار اتصال الأجهزة...",
        "devices_stopped_text": "الخادم متوقف.",
        "menu_file": "&ملف",
        "menu_file_exit": "&خروج",
        "menu_file_restart_admin": "إعادة التشغيل ك&مسؤول",
        "menu_file_about": "&حول PCLink",
        "menu_settings": "&إعدادات",
        "change_port_btn": "تغيير ال&منفذ...",
        "regen_api_key_btn": "إعادة &إنشاء مفتاح API...",
        "menu_language": "&اللغة",
        "language_changed_title": "تغيير اللغة",
        "language_changed_msg": "سيتم تغيير اللغة في المرة القادمة التي تبدأ فيها التطبيق.",
        "start_with_os_chk": "البدء مع نظام التشغيل",
        "start_with_os_tooltip": "إذا تم تحديده، سيبدأ PCLink تلقائيًا عند تسجيل الدخول.",
        "minimize_on_close_chk": "التصغير إلى شريط المهام عند الإغلاق",
        "use_https_chk": "استخدام اتصال آمن (HTTPS)",
        "use_https_tooltip": "يمكّن تشفير SSL/TLS. موصى به.",
        "allow_insecure_shell_chk": "السماح بالوصول غير الآمن للطرفية",
        "allow_insecure_shell_tooltip": "تحذير: يسمح للطرفية بالعمل بدون مصادقة مفتاح API. استخدمه فقط على الشبكات الموثوقة.",
        "show_startup_notification_chk": "إظهار إشعار عند بدء التشغيل",
        "tray_tooltip": "خادم PCLink",
        "tray_show": "إظهار PCLink",
        "setting_saved_title": "تم حفظ الإعداد",
        "restart_server_prompt": "يجب إعادة تشغيل الخادم حتى يسري هذا التغيير. هل تريد إعادة تشغيل الخادم الآن؟",
        "regen_api_key_confirm": "هل أنت متأكد من أنك تريد إنشاء مفتاح API جديد؟ ستحتاج جميع الأجهزة المتصلة حاليًا إلى إعادة الإقران.",
        "api_key_updated_title": "تم تحديث مفتاح API",
        "api_key_updated_msg": "تم إنشاء مفتاح API جديد بنجاح.",
        "change_port_prompt": "أدخل المنفذ الجديد للخادم:",
        "https_warning_title": "تحذير أمني",
        "https_warning_msg": "لا يوصى بتعطيل HTTPS. لن يتم تشفير اتصالك.",
        "insecure_shell_warning_title": "تحذير أمني",
        "insecure_shell_warning_msg": "تمكين هذا الخيار يسمح لأي شخص على شبكتك بالوصول إلى طرفية الخادم. هذا يمثل خطرًا أمنيًا كبيرًا. هل أنت متأكد من أنك تريد المتابعة؟",
        "confirm_exit_title": "تأكيد الخروج",
        "confirm_exit_text": "هل أنت متأكد من رغبتك في الخروج؟ سيتم إيقاف الخادم.",
        "exit_button": "خروج",
        "minimize_button": "تصغير إلى الشريط",
        "cancel_button": "إلغاء",
        "check_updates_on_startup_chk": "فحص التحديثات عند بدء التشغيل",
        "check_updates_now_btn": "فحص التحديثات الآن",
        "update_available_title": "تحديث متاح",
        "update_available_msg": "إصدار جديد من PCLink متاح.",
        "no_updates_title": "لا توجد تحديثات",
        "no_updates_msg": "أنت تستخدم أحدث إصدار من PCLink.",
        "pairing_request_title": "طلب إقران جهاز",
        "pairing_request_text": "الجهاز '{device_name}' يريد الاتصال بهذا الخادم. السماح بالاتصال؟",
    },
    "es": {
        "lang_name": "Español",
        "is_rtl": "false",
        "window_title": "Servidor PCLink",
        "admin_suffix": " (Administrador)",
        "server_running_status": "Servidor en MARCHA",
        "server_stopped_status": "Servidor DETENIDO",
        "start_server_btn": "Iniciar Servidor",
        "stop_server_btn": "Detener Servidor",
        "ip_addr_label": "Dirección IP:",
        "port_label": "Puerto:",
        "api_key_label": "Clave API:",
        "copy_ip_tooltip": "Copiar IP",
        "copy_port_tooltip": "Copiar Puerto",
        "copy_key_tooltip": "Copiar Clave API",
        "qr_stopped_text": "Servidor detenido. Inicie el servidor para ver el código QR.",
        "qr_error_text": "No se pudo generar el código QR. Compruebe si el servidor está funcionando.",
        "devices_group": "Dispositivos Conectados",
        "devices_stopped_text": "El servidor está detenido.",
        "devices_waiting_text": "Esperando que se conecten dispositivos...",
        "menu_file": "&Archivo",
        "menu_file_exit": "&Salir",
        "menu_file_restart_admin": "&Reiniciar como Administrador",
        "menu_file_about": "&Acerca de PCLink",
        "menu_settings": "&Ajustes",
        "change_port_btn": "Cambiar &Puerto...",
        "regen_api_key_btn": "&Regenerar Clave API...",
        "menu_language": "&Idioma",
        "language_changed_title": "Idioma Cambiado",
        "language_changed_msg": "El idioma cambiará la próxima vez que inicie la aplicación.",
        "start_with_os_chk": "Iniciar con el Sistema Operativo",
        "start_with_os_tooltip": "Si está marcado, PCLink se iniciará automáticamente cuando inicie sesión.",
        "minimize_on_close_chk": "Minimizar a la bandeja al cerrar",
        "use_https_chk": "Usar Conexión Segura (HTTPS)",
        "use_https_tooltip": "Habilita el cifrado SSL/TLS. Recomendado.",
        "allow_insecure_shell_chk": "Permitir Acceso Inseguro a la Terminal",
        "allow_insecure_shell_tooltip": "ADVERTENCIA: Permite que la terminal se ejecute sin autenticación de clave API. Úselo solo en redes de confianza.",
        "show_startup_notification_chk": "Mostrar notificación al iniciar",
        "tray_tooltip": "Servidor PCLink",
        "tray_show": "Mostrar PCLink",
        "setting_saved_title": "Ajuste Guardado",
        "restart_server_prompt": "El servidor debe reiniciarse para que este cambio surta efecto. ¿Reiniciar el servidor ahora?",
        "regen_api_key_confirm": "¿Está seguro de que desea generar una nueva clave API? Todos los dispositivos actualmente conectados deberán volver a emparejarse.",
        "api_key_updated_title": "Clave API Actualizada",
        "api_key_updated_msg": "Se ha generado una nueva clave API con éxito.",
        "change_port_prompt": "Ingrese el nuevo puerto para el servidor:",
        "https_warning_title": "Advertencia de Seguridad",
        "https_warning_msg": "No se recomienda deshabilitar HTTPS. Su conexión no estará encriptada.",
        "insecure_shell_warning_title": "Advertencia de Seguridad",
        "insecure_shell_warning_msg": "Habilitar esto permite que cualquiera en su red acceda a la terminal del servidor. Esto es un riesgo de seguridad significativo. ¿Está seguro de que desea continuar?",
        "confirm_exit_title": "Confirmar Salida",
        "confirm_exit_text": "¿Está seguro de que desea salir? El servidor se detendrá.",
        "exit_button": "Salir",
        "minimize_button": "Minimizar a la Bandeja",
        "cancel_button": "Cancelar",
        "check_updates_on_startup_chk": "Buscar Actualizaciones al Iniciar",
        "check_updates_now_btn": "Buscar Actualizaciones Ahora",
        "update_available_title": "Actualización Disponible",
        "update_available_msg": "Una nueva versión de PCLink está disponible.",
        "no_updates_title": "Sin Actualizaciones",
        "no_updates_msg": "Está ejecutando la última versión de PCLink.",
        "pairing_request_title": "Solicitud de Emparejamiento de Dispositivo",
        "pairing_request_text": "El dispositivo '{device_name}' quiere conectarse a este servidor. ¿Permitir conexión?",
    },
    "fr": {
        "lang_name": "Français",
        "is_rtl": "false",
        "window_title": "Serveur PCLink",
        "admin_suffix": " (Administrateur)",
        "server_running_status": "Serveur en MARCHE",
        "server_stopped_status": "Serveur ARRÊTÉ",
        "start_server_btn": "Démarrer le Serveur",
        "stop_server_btn": "Arrêter le Serveur",
        "ip_addr_label": "Adresse IP:",
        "port_label": "Port:",
        "api_key_label": "Clé API:",
        "copy_ip_tooltip": "Copier l'adresse IP",
        "copy_port_tooltip": "Copier le Port",
        "copy_key_tooltip": "Copier la Clé API",
        "qr_stopped_text": "Le serveur est arrêté. Démarrez le serveur pour afficher le code QR.",
        "qr_error_text": "Impossible de générer le code QR. Vérifiez si le serveur est en cours d'exécution.",
        "devices_group": "Appareils Connectés",
        "devices_stopped_text": "Le serveur est arrêté.",
        "devices_waiting_text": "En attente de la connexion d'appareils...",
        "menu_file": "&Fichier",
        "menu_file_exit": "&Quitter",
        "menu_file_restart_admin": "&Redémarrer en tant qu'administrateur",
        "menu_file_about": "&À propos de PCLink",
        "menu_settings": "&Paramètres",
        "change_port_btn": "Changer le &Port...",
        "regen_api_key_btn": "&Régénérer la Clé API...",
        "menu_language": "&Langue",
        "language_changed_title": "Langue Modifiée",
        "language_changed_msg": "La langue changera au prochain démarrage de l'application.",
        "start_with_os_chk": "Démarrer avec le Système d'Exploitation",
        "start_with_os_tooltip": "Si coché, PCLink démarrera automatiquement à l'ouverture de session.",
        "minimize_on_close_chk": "Réduire dans la barre d'état système à la fermeture",
        "use_https_chk": "Utiliser une Connexion Sécurisée (HTTPS)",
        "use_https_tooltip": "Active le cryptage SSL/TLS. Recommandé.",
        "allow_insecure_shell_chk": "Autoriser l'accès non sécurisé au terminal",
        "allow_insecure_shell_tooltip": "ATTENTION : Permet au terminal de fonctionner sans authentification par clé API. À utiliser uniquement sur des réseaux de confiance.",
        "show_startup_notification_chk": "Afficher la notification au démarrage",
        "tray_tooltip": "Serveur PCLink",
        "tray_show": "Afficher PCLink",
        "setting_saved_title": "Paramètre Enregistré",
        "restart_server_prompt": "Le serveur doit être redémarré pour que ce changement prenne effet. Redémarrer le serveur maintenant ?",
        "regen_api_key_confirm": "Êtes-vous sûr de vouloir générer une nouvelle clé API ? Tous les appareils actuellement connectés devront être ré-appairés.",
        "api_key_updated_title": "Clé API Mise à Jour",
        "api_key_updated_msg": "Une nouvelle clé API a été générée avec succès.",
        "change_port_prompt": "Entrez le nouveau port pour le serveur :",
        "https_warning_title": "Avertissement de Sécurité",
        "https_warning_msg": "La désactivation de HTTPS n'est pas recommandée. Votre connexion ne sera pas cryptée.",
        "insecure_shell_warning_title": "Avertissement de Sécurité",
        "insecure_shell_warning_msg": "Activer cette option permet à quiconque sur votre réseau d'accéder au terminal du serveur. C'est un risque de sécurité important. Êtes-vous sûr de vouloir continuer ?",
        "confirm_exit_title": "Confirmer la fermeture",
        "confirm_exit_text": "Êtes-vous sûr de vouloir quitter ? Le serveur sera arrêté.",
        "exit_button": "Quitter",
        "minimize_button": "Réduire",
        "cancel_button": "Annuler",
        "check_updates_on_startup_chk": "Vérifier les Mises à Jour au Démarrage",
        "check_updates_now_btn": "Vérifier les Mises à Jour Maintenant",
        "update_available_title": "Mise à Jour Disponible",
        "update_available_msg": "Une nouvelle version de PCLink est disponible.",
        "no_updates_title": "Aucune Mise à Jour",
        "no_updates_msg": "Vous utilisez la dernière version de PCLink.",
        "pairing_request_title": "Demande d'Appairage d'Appareil",
        "pairing_request_text": "L'appareil '{device_name}' veut se connecter à ce serveur. Autoriser la connexion ?",
    },
}
